services:
  postgres:
    image: postgres
    container_name: morticia-postgres
    ports:
      - "5432:5432/tcp"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: morticia-pgadmin
    restart: unless-stopped
    ports:
     - "8998:80"
    env_file:
     - .env
    depends_on:
     - postgres
    links:
      - postgres
