[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "starcatcher"
dynamic = ["version"]
dependencies = [
    "dotenv",
    "discord-py",
    "pygithub",
    "gitpython"
]
requires-python = ">= 3.10"
license = "GPL-3.0-only"
