"""create known prs table and known file changes table

Revision ID: 75a758ee8e5a
Revises: a924de8e6dd7
Create Date: 2025-09-03 04:37:51.324025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a758ee8e5a'
down_revision: Union[str, Sequence[str], None] = 'a924de8e6dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_pull_requests',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changed_files', sa.Integer(), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('ref_base', sa.String(), nullable=False),
    sa.Column('ref_head', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.Integer(), nullable=True),
    sa.Column('merged_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['known_repos.repo_id'], name=op.f('fk_known_pull_requests_repo_id_known_repos')),
    sa.PrimaryKeyConstraint('pull_request_id', 'repo_id', name=op.f('pk_known_pull_requests'))
    )
    op.create_table('known_file_changes',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('previous_file_path', sa.String(), nullable=True),
    sa.Column('patch', sa.String(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_path', 'repo_id'], ['known_files.file_path', 'known_files.repo_id'], name=op.f('fk_known_file_changes_file_path_repo_id_known_files')),
    sa.ForeignKeyConstraint(['pull_request_id', 'repo_id'], ['known_pull_requests.pull_request_id', 'known_pull_requests.repo_id'], name=op.f('fk_known_file_changes_pull_request_id_known_pull_requests')),
    sa.ForeignKeyConstraint(['repo_id'], ['known_repos.repo_id'], name=op.f('fk_known_file_changes_repo_id_known_repos')),
    sa.PrimaryKeyConstraint('pull_request_id', 'repo_id', 'file_path', name=op.f('pk_known_file_changes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('known_file_changes')
    op.drop_table('known_pull_requests')
    # ### end Alembic commands ###
