"""make sha column nullable

Revision ID: 9f0255a4003a
Revises: 922b636258bd
Create Date: 2025-09-12 17:27:16.425900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0255a4003a'
down_revision: Union[str, Sequence[str], None] = '922b636258bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('known_file_changes', 'sha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # op.drop_constraint(op.f('fk_known_file_changes_file_path_repo_id_known_files'), 'known_file_changes', type_='foreignkey')
    # op.drop_constraint(op.f('fk_known_file_changes_pull_request_id_known_pull_requests'), 'known_file_changes', type_='foreignkey')
    # op.create_foreign_key(op.f('fk_known_file_changes_pull_request_id_known_pull_requests'), 'known_file_changes', 'known_pull_requests', ['pull_request_id'], ['pull_request_id'])
    # op.create_foreign_key(op.f('fk_known_file_changes_file_path_known_files'), 'known_file_changes', 'known_files', ['file_path'], ['file_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('fk_known_file_changes_file_path_known_files'), 'known_file_changes', type_='foreignkey')
    # op.drop_constraint(op.f('fk_known_file_changes_pull_request_id_known_pull_requests'), 'known_file_changes', type_='foreignkey')
    # op.create_foreign_key(op.f('fk_known_file_changes_pull_request_id_known_pull_requests'), 'known_file_changes', 'known_pull_requests', ['pull_request_id', 'repo_id'], ['pull_request_id', 'repo_id'])
    # op.create_foreign_key(op.f('fk_known_file_changes_file_path_repo_id_known_files'), 'known_file_changes', 'known_files', ['file_path', 'repo_id'], ['file_path', 'repo_id'])
    op.alter_column('known_file_changes', 'sha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
