"""create known files table

Revision ID: a924de8e6dd7
Revises: 2a24e2410cbd
Create Date: 2025-09-03 02:26:27.153380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a924de8e6dd7'
down_revision: Union[str, Sequence[str], None] = '2a24e2410cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_files',
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['known_repos.repo_id'], name=op.f('fk_known_files_repo_id_known_repos')),
    sa.PrimaryKeyConstraint('repo_id', 'file_path', name=op.f('pk_known_files'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('known_files')
    # ### end Alembic commands ###
