"""create table project_latest_addition

Revision ID: b5484cdc4753
Revises: 9f0255a4003a
Create Date: 2025-09-23 16:10:01.556123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5484cdc4753'
down_revision: Union[str, Sequence[str], None] = '9f0255a4003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_latest_addition',
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('branch', name=op.f('pk_project_latest_addition'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_latest_addition')
    # ### end Alembic commands ###
